### ISSUE TITLE
Implement FluendNode extension method for CoffeeScript existential operator (?).

### ISSUE THREAD

**Issue by michaelhidalgo** [o2platform/fluentnode#42]
As described here http://coffeescript.org, CoffeeScript has a mechanism in place to verify the existence and nullability of an object by using the existential operator ?.

According to the documentation, using the existential operator ? it is a safer way  to check null and undefined.

**Comment by DinisCruz** [comment]
does https://github.com/o2platform/fluentnode/issues/29 address that?

**Comment by DinisCruz** [comment]
not sure how we can wrap that one in an Extension method

**Comment by michaelhidalgo** [comment]
Actually it seems like https://github.com/o2platform/fluentnode/issues/29 address it. As far as I can see in the unit test in here https://github.com/o2platform/fluentnode/commit/c088d032269787437bef2579b39a93ac0b9a97f1#diff-469a188808ba93eeb35cf05b58da16deR7 

and here https://github.com/o2platform/fluentnode/commit/c088d032269787437bef2579b39a93ac0b9a97f1#diff-469a188808ba93eeb35cf05b58da16deR6

**Comment by DinisCruz** [comment]
yeah, I think that is the best we can do. 

@michaelhidalgo I think we can close this issue

**Comment by michaelhidalgo** [comment]
Closing this issue.
