### ISSUE TITLE
[Q] delete temp file created by #80 solution

### ISSUE THREAD

**Issue by DinisCruz** [o2platform/fluentnode#82]
see https://github.com/o2platform/fluentnode/pull/80/files#r28220948

![image](https://cloud.githubusercontent.com/assets/656739/7112070/07931fd8-e1be-11e4-843c-d769a8ec43e3.png)

**Comment by michaelhidalgo** [comment]
yeah you are right, let me fix it.

**Comment by DinisCruz** [comment]
Fix merged and tests passing https://ci.appveyor.com/project/DinisCruz/fluentnode/build/1.0.11
